version: "3.5"

networks:
  monica:
  monica-private:

volumes:
  monica:
  monica-db:

secrets:
  monica_admin_password:
    name: ${STACK_NAME:-technocore}_monica_admin_password
    external: true
  monica_monica_db_password:
    name: ${STACK_NAME:-technocore}_monica_monica_db_password
    external: true
  monica_db_monica_password:
    name: ${STACK_NAME:-technocore}_monica_db_monica_password
    external: true

services:
  # Uncomment this if Traefik will be used for routing traffick to this service.
  ingress:
    networks:
      - monica

  monica:
    deploy:
      labels:
        - traefik.frontend.rule=$MONICA_ROUTING_LABEL
        - traefik.frontend.priority=$MONICA_ROUTING_LABEL_PRIORITY
        # You'll need to set application's port here.
        - traefik.port=80
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress
        - traefik.docker.network=${STACK_NAME:-technocore}_monica
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      #- MQTT_USER=${monica}
      - DB_HOST=monica_db
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD={{"{{DOCKER-SECRET:monica_db_password}}"}}
      - APP_URL=https://monica.$DOMAIN
      - APP_TRUSTED_PROXIES=*
      - APP_DISABLE_SIGNUP=false
      - APP_ENV=production
    image: ${image_provider:-scififarms}/technocore-monica:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - monica
      - monica-private
    secrets:
      - source: monica_admin_password
        target: admin_password
      - source: monica_monica_db_password
        target: monica_db_password
    volumes:
      - ${TECHNOCORE_DATA}/monica:/var/www/html/storage
      #- ${DEV_MOUNT_MONICA_MIGRATIONS:-$EMPTY_MOUNT}

  monica_db:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    environment:
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_ROOT_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
      - MYSQL_PASSWORD={{"{{DOCKER-SECRET:monica_password}}"}}
      - TZ=${TZ}
    #image: ${image_provider:-scififarms}/technocore-nextcloud-db:${TAG:-latest}
    image: ${image_provider:-scififarms}/technocore-maria-db:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - monica-private
    secrets:
      - source: monica_db_monica_password
        target: monica_password
    volumes:
      - ${TECHNOCORE_DATA}/monica_db:/var/lib/mysql
